---
driver:
  name: vagrant
  gui: true
  linked_clone: true

platforms:
  - name: ansibleserver
    driver_plugin: vagrant
    driver_config:
      box: alvaro/wouter7
      network:
      - [ 'private_network', { ip: '172.28.128.10' } ]
      provision: true
      vagrantfiles:
        - configure/linux/ansible/provision.rb
    transport:
      max_ssh_sessions: 1
    provisioner:
      name: ansible_playbook
      roles_path: ../
      role_name: windows_prereqs
      ansible_connection: winrm
      ansible_inventory: inventory/hosts
      require_windows_support: true
      require_chef_for_busser: false
      ansible_host_key_checking: false
      ansible_verbose: true
      ansible_verbosity: 4
      playbook: playbook.yml
    verifier:
      name: shell
      command: echo 'Skipping Verify'

  - name: win2012r2core
    driver_config:
      box: mwrock/Windows2012R2
      communicator: winrm
      network:
      - [ 'private_network', { ip: '172.28.128.11' } ]
      - [ 'forwarded_port', { guest: 80, host: 8080 } ]
       # needed to force provision of the vagrantfile
      provision: true
      # needed to run the ConfigureRemotingForAnsible.ps1
      vagrantfiles:
        - configure/windows/2012R2/provision.rb
    transport:
      name: winrm
    verifier:
      name: inspec
      format: documentation
      inspec_tests:
        - test/integration/default
    provisioner:
      name: shell

suites:
  - name: default
