source "https://rubygems.org"

gem "inspec"

group :test do
  gem "bundler", "~> 2.0"
  gem "minitest", "~> 5.5"
  gem "rake", ["~> 12.3", ">= 12.3.3"]
  gem "simplecov", "~> 0.10"
  gem "kitchen-pester"
  gem "winrm-fs"
  gem "winrm"
end

group :integration do
  gem "test-kitchen", "~> 1.4"
  gem "kitchen-ansible"
  gem "kitchen-vagrant"
  gem "kitchen-inspec"
  gem "kitchen-pester"
  gem "winrm-fs"
  gem "winrm"
  gem "busser"
  gem "concurrent-ruby", "~> 1.0"
end
